#
# To compile for Linux x86_64
#
include(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(GFRAMEWORK_TARGET_OS "linux")
set(GFRAMEWORK_TARGET_ARCH "x86-64")
set(GFRAMEWORK_TARGET_SOC "")
set(GFRAMEWORK_TARGET_COMPILER "gcc")
set(GFRAMEWORK_SHARED_LIB_EXT "so")

set(GFRAMEWORK_IMPORT_API )
set(GFRAMEWORK_EXPORT_API )

